Предназначен для автоматизации запросов к сервисам, которые предоставляют публичный API для управления. Это может быть REST API, SOAP API или любой другой API, который принимает HTTP запросы.

==== Как пользоваться?

* Создайте (или выберите существующий) шаблон HTTP запроса, руководствуясь документацией к выбранному API - опции шаблона позволяют смоделировать практически любой запрос. В шаблоне используйте placeholder'ы, в тех местах, где необходимо подставить информацию из списка или таблицы параметров для замены;
* Укажите список и заполните таблицу параметров для замены (при необходимости). Список параметров для замены должен содержать по крайней мере одну строку - количество выполняемых запросов равно количеству строк в списке;
* Запустите процесс и перейдите на вкладку **Журнал** для его отслеживания.

==== Настройки

В выпадающем списке **Шаблон** находятся созданные вами шаблоны HTTP запросов. Вы можете добавлять новые и редактировать существующие, используя иконку меню, которая находится справа от этого списка. Используйте опцию **Предварительный просмотр**, чтобы быстро проверить настройки выбранного шаблона.

Таблица **Параметры** содержит значения для замены, которые остаются постоянными при выполнении каждого отдельного HTTP запроса или генерируются приложением автоматически. Добавление и удаление параметров выполняется через контекстное меню.

* CONSTANT - постоянное значение, которое вы должны указать вручную, до запуска;
* PASSWORD - случайная строка заданной длины, сгенерированная из символов `[a-ZA-Z0-9]`;
* PASSWORD_BASE64 - то же самое, что и предыдущий пункт, но значение будет преобразовано в BASE64 строку после генерации;
* UUID - 16-байтный https://ru.wikipedia.org/wiki/UUID[уникальный идентификатор] (например, `718b5495-4511-4064-8923-560ec2127d23`).

**Список параметров для замены** представляет собой CSV (comma separated values) таблицу. В качестве разделителя элементов строки можно использовать запятую или точку с запятой. Вот так его видит приложение:

----
_csv0,_csv1,_csv2
_csv0,_csv1,_csv2
----

Группа параметров **Аутентификация**, как следует из названия, предназначена для аутентификации пользователя на стороне API при выполнении HTTP запроса. На данный момент поддерживается только https://ru.wikipedia.org/wiki/Аутентификация_в_Интернете#Базовая_аутентификация[базовая аутентификация]. Вы можете достичь того же эффекта просто добавив HTTP заголовок вида `Authorization: Basic XYZ` в соответствующее поле шаблона, где `XYZ` вычисляется по формуле `base64(username + password)`. В этом случае вам не потребуется указывать учетную запись при каждом запуске приложения, но данные будут сохранены в конфигурационном файле [.underline]#в открытом виде#.

**Таймаут между запросами** предназначен для настройки времени (в миллисекундах), которое приложение отсчитывает перед тем как выполнять каждый последующий запрос. Используйте этот параметр, чтобы не перегружать удаленный сервер большим количеством запросов за короткий промежуток времени, или наоборот, сократить общее время выполнения за счет уменьшения таймаута.

==== Журнал

На этой вкладке отображаются результаты всех выполненных запросов. Вы можете экспортировать лог запросов в файл полностью, или скопировать выделенные строки таблицы в буфер обмена стандартной комбинацией клавиш `CTRL + C`.

==== Пример

Для использования клиента необходимо создать шаблон, описывающий формат HTTP запроса для конкретного сервиса, предоставляемого удаленным API. При создании шаблона используются следующие поля:

* Имя - уникальное имя шаблона;
* URL - полный адрес и https://ru.wikipedia.org/wiki/HTTP#Методы[HTTP метод] запроса;
* Заголовки HTTP - дополнительные https://ru.wikipedia.org/wiki/HTTP#Методы[HTTP заголовки] запроса;
* Тело сообщения - полезная нагрузка запроса;
* Таймаут ожидания ответа - разные запросы требуют различного времени от сервера на обработку. Данный параметр регулирует время ожидания ответа по истечении которого будет выполнен новый запрос, а текущий отмечен как неудавшийся;
* Описание - любая дополнительная или справочная информация к шаблону.

Как правило, все указанные параметры однозначно описываются документацией к соответствующему API. В качестве примера, рассмотрим открытый API для тестирования https://jsonplaceholder.typicode.com/guide.html[JSONPlaceholder]. Согласно документации, так выглядит создание ресурса в каталоге `/posts`.

[source,javascript]
----
fetch('https://jsonplaceholder.typicode.com/posts', {
  method: 'POST',
  body: JSON.stringify({
    title: 'foo',
    body: 'bar',
    userId: 1
  }),
  headers: {
    "Content-type": "application/json; charset=UTF-8"
  }
})
----

Следовательно, соответствующий шаблон должен выглядеть следующим образом:

* URL
+
`POST, https://jsonplaceholder.typicode.com/posts`
+
* Заголовки HTTP
+
`Content-type: application/json; charset=UTF-8`
+
* Тело сообщения
+
`{ title: '%(_csv0) ел кашу', body: '%(test)', userId: 1 }``
+


Правила замены при выполнении запроса:

* формат параметров для замены имеет вид: `%(имя_параметра)`, где `имя_параметра`:
** один из встроенных параметров:
*** `_index0` - порядковый номер строки списка начиная с 0;
*** `_index1` - порядковый номер строки списка начиная с 1;
** название параметра из таблицы *Параметры*;
** идентификатор параметра из *Списка для замены*. В этом случае, имя параметра имеет фиксированный вид `_csvX`, где `X` - порядковый номер начиная с 0.
* в обычном режиме замена осуществляется в полях URL, заголовках и теле сообщения; в режиме объединения запросов замена выполняется только в теле сообщения.

Возвращаясь к примеру, если список для замены имеет вид:

----
Пушкин,Александр
Есенин,Сергей
Лермонтов,Михаил
----

А в таблице параметров создан параметр `test` с типом `CONSTANT`, которому назначено значение `12345`, то будет выполнено три следующих HTTP запроса.

----
POST https://jsonplaceholder.typicode.com/posts
{ title: 'Пушкин ел кашу', body: '12345', userId: 1 }

POST https://jsonplaceholder.typicode.com/posts
{ title: 'Есенин ел кашу', body: '12345', userId: 1 }

POST https://jsonplaceholder.typicode.com/posts
{ title: 'Лермонтов ел кашу', body: '12345', userId: 1 }
----

Таким образом, в обычном режиме количество выполняемых запросов равно количеству строк в списке для замены. Параметр `_csv1` был проигнорирован, поскольку соответствующее ему выражение для замены `%(_csv1)` нигде в шаблоне не фигурирует.

[NOTE]
====
Один и тот же список для замены можно использовать многократно в нескольких шаблонах, просто задействуя в каждом из них только нужные колонки.
====

==== Режим объединения запросов

Режим объединения запросов настраивается на вкладке *Объединение* соответствующего шаблона, и включается при условии, что значение параметра *Количество объединяемых запросов* больше `0`.

В этом режиме осуществляется объединение тела (полезной нагрузки) нескольких HTTP запросов - в один. Таким образом, сокращается количество выполняемых запросов, что, в некоторых случаях, позволяет существенно сократить общее время выполнения. Для данного режима также необходима поддержка такого формата запросов со стороны API - руководствуйтесь документацией.

[NOTE]
====
Обратите внимание, что для обработки такого объединенного запроса, серверу всегда требуется больше времени, чем для обработки одиночного. Поэтому не забудьте увеличить значение параметра *Таймаут ожидания ответа* соответствующим образом.
====

Посмотрим на предыдущий пример. Все три запроса можно объединить в один. Для этого полезная нагрузка должна иметь следующий вид:

[source,json]
----
[
    { title: 'Пушкин ел кашу', body: '12345', userId: 1 },
    { title: 'Есенин ел кашу', body: '12345', userId: 1 },
    { title: 'Лермонтов ел кашу', body: '12345', userId: 1 }
]
----

Этого можно добиться установив следующие значения параметров:

* *Количество объединяемых запросов* = 5;
+
Количество объединяемых запросов может быть выбрано любым, кратным пяти. Если количество строк в списке не делится на пять без остатка, то это отразится только на последнем запросе. Например, для 12 строк будет выполнено 3 запроса (`5 + 5 + 2`).
+

* *Шаблон объединения* = `[%(_batch)]`;
+
`%(_batch)` - это специальный параметр, значение которого представляет собой результат объединения полезной нагрузки нескольких запросов. Объединение выполняется после замены placeholder'ов, а результат вставляется на указанное место (в данном случае, между квадратных скобок).
+
Элементы в выражении `%(_batch)` разделяются друг от друга с помощью строки *Разделителя*, которая указывается в соответствующем поле.
+
Также как и *Теле сообщения*, в шаблоне объединения вы можете указывать placeholder'ы, которые будут заменены соответствующими значениями при выполнении запроса. Например, такая конструкция может быть использована для JSON RPC API от Zabbix:

+
[source,json]
----
{
    "jsonrpc": "2.0",
    "method": "trigger.create",
    "params": [%(_batch)],
    "auth": "%(token)",
    "id": 1
}
----
+