package org.telekit.ui.tools.common;

import javafx.scene.control.TableRow;
import javafx.scene.control.cell.TextFieldTableCell;
import javafx.util.StringConverter;

public class ParamValueTableCell extends TextFieldTableCell<Param, String> {

    private static final String AUTOGENERATED = "<autogenerated>";

    public ParamValueTableCell(StringConverter<String> converter) {
        super(converter);
    }

    @Override
    public void updateItem(String value, boolean empty) {
        super.updateItem(value, empty);

        TableRow<Param> row = getTableRow();
        if (row == null) return;

        Param param = row.getItem();
        if (param != null) {
            setEditable(!param.isAutoGenerated());
            if (param.isAutoGenerated()) setText(AUTOGENERATED);
        }
    }
}