package org.telekit.ui.tools.common;

import org.telekit.base.domain.KeyValue;

import java.util.Map;
import java.util.Set;

import static org.apache.commons.lang3.StringUtils.isBlank;

public final class ReplacementUtils {

    public static boolean putTemplatePlaceholders(Map<String, String> accumulator, Set<Param> params) {
        boolean hasBlankValues = false;
        for (Param param : params) {
            KeyValue<String, String> kv = Param.resolve(param);
            accumulator.put(kv.getKey(), kv.getValue());
            if (!param.isAutoGenerated() && isBlank(param.getValue())) hasBlankValues = true;
        }
        return hasBlankValues;
    }

    public static void putCsvPlaceholders(Map<String, String> accumulator, String[] row) {
        for (int index = 0; index < row.length; index++) {
            accumulator.put("_csv" + index, row[index]);
        }
    }

    // Provides user an ability to include record index into template pattern.
    // _index0 - contains current row index, starting from 0
    // _index1 - contains current row index, starting from 1
    public static void putIndexPlaceholders(Map<String, String> accumulator, int idx) {
        accumulator.put("_index0", String.valueOf(idx));
        accumulator.put("_index1", String.valueOf(idx + 1));
    }
}
