Предназначен для генерации последовательностей, в основе которых лежит изменение числовых значений в определенных границах.

Использование утилиты проще всего показать на примере. Рассмотрим задачу генерации адреса физического порта на устройстве. По условиям, адрес порта имеет вид: `frame-slot-port`. При этом:

* frame - изменяется от 0 до 1;
* slot - изменяется от 1 до 2;
* port - изменяется от 1 до 4.

Генератор последовательностей поддерживает до 4-х значений, которые можно использовать при формировании шаблона. Пусть A - frame, B - slot, C - port, тогда шаблон адреса физического порта будет иметь вид `%(A)-%(B)-%\(C)`.

Для каждого параметра в отдельности необходимо указать три значения:

* начальное значение;
* величина шага (в большую или меньшую сторону);
* количество итераций.

Согласно условиям задачи это: `A: 0, 1, 2`; `B: 1, 1, 4`; `C: 1, 1, 4`. Применив данные параметры получим следующий список:

----
0-1-1
0-1-2
0-1-3
0-1-4
0-2-1
0-2-2
0-2-3
0-2-4
1-1-1
1-1-2
1-1-3
1-1-4
1-2-1
1-2-2
1-2-3
1-2-4
----

Аналогичным образом можно сгенерировать, как список IP-адресов, так и элементарные последовательности, вроде списка номеров от 100 до 200.
