==== CIC Table

Утилита для поиска и отображения информации по ISUP CIC (channel identification code). Отображается соответствие CIC номеру потока E1.

==== SPC Converter

Утилита для преобразования кода пункта сигнализации ОКС-7 между различными формами записи.

Длина кода пункта сигнализации:

* 14 бит - европейский (ITU) стандарт;
* 24 бит - североамериканский (ANSI) стандарт.

Дополнительно указывается формат записи для введенного кода пункта сигнализации:

* Простые форматы:

** DECIMAL - десятичная форма записи;
** BINARY - двоичная форма записи;
** HEX - шестнадцатеричная форма записи;

* ITU форматы:

** `3-8-3` - стандартная форма записи (world geographical zone + geographical area + signaling point ID);
** `8-6` - российская национальная форма записи (geographical area + signaling point ID). Применяется только для записи кода пункта сигнализации внутри страны;
* ANSI форматы:
** `8-8-8` - стандартная форма записи (network indicator + network cluster + network cluster member).

Правильно укажите исходные данные и после нажатия кнопки *Обновить* будут отображены все доступные формы записи кода пункта сигнализации.
