Позволяет по заранее заданному шаблону генерировать текстовые файла произвольного формата с повторяющейся структурой. Это могут быть скрипты, CSV, JSON или XML-файлы. Если текстовый файл, или его часть, можно описать как:

----
начало документа (опционально)
элемент 1
элемент 2
...
элемент N
конец документа (опционально)
----

_..._ то его можно сгенерировать с помощью данной утилиты.

==== Как пользоваться?

* Создайте (или выберите существующий) шаблон файла. В шаблоне используйте placeholder'ы, в тех местах, где необходимо подставить информацию из списка или таблицы параметров для замены;
* Укажите список и заполните таблицу параметров для замены (при необходимости). Список параметров для замены должен содержать по крайней мере одну строку;
* Запустите процесс генерации. Вы можете выбрать между созданием нового файла - если старый файл с таким именем уже существует, то он будет перезаписан, или записью в конец существующего файла. Последний вариант помогает создавать более сложные структуры или записывать в один файл несколько элементов разного типа.

==== Настройки

В выпадающем списке **Шаблон** находятся созданные вами шаблоны файлов. Вы можете добавлять новые и редактировать существующие, используя иконку меню, которая находится справа от этого списка. Используйте опцию **Предварительный просмотр**, чтобы быстро проверить настройки выбранного шаблона.

Таблица **Параметры** содержит значения для замены, которые остаются постоянными для каждого отдельного элемента или генерируются приложением автоматически. Добавление и удаление параметров выполняется через контекстное меню.

[NOTE]
====
Правила замены параметров не отличаются для описанных для API клиента. Вы также можете использовать подсказки, если значение какого-либо параметра ограничено некоторым типовым набором.
====

**Список параметров для замены** представляет собой CSV (comma separated values) таблицу. В качестве разделителя элементов строки можно использовать запятую или точку с запятой.

[NOTE]
====
Один и тот же список для замены можно использовать многократно в нескольких шаблонах, просто задействуя в каждом из них только нужные колонки.

Для генерации файлов со сложной структурой, вы можете использовать режим записи в конец существующего файла и последовательную генерацию в него из нескольких шаблонов.
====

==== Пример

Для использования генератора необходимо создать шаблон, описывающий структуру целевого текстового файла. При создании шаблона используются следующие поля:

* Имя - уникальное имя шаблона;
* Начало документа - любое количество строк, которое будет записано в самое начало файла (например, заголовок CSV);
* Разделитель - если файл может быть представлен в виде таблицы (например, это актуально для CSV), то указанный разделитель будет использован для предварительного просмотра файла в виде таблицы. На сгенерированный файл данный параметр никакого влияния не оказывает;
* Элемент - повторяющийся элемент шаблона. Это может быть строка, несколько строк, узел JSON или XML документа - любой повторяющийся текст;
* Конец документа - любое количество строк, которое будет записано в самый конец файла (например, закрывающий XML тэг или список команд для сброса настроек скрипта);
* Формат файла - кодировка файла и символ разделителя строк;
* Описание - любая дополнительная или справочная информация к шаблону.

Предположим, что необходимо сгенерировать скрипт, который состоит из набора команд, т.е. структура целевого файла имеет вид:

----
CREATE_SUBSCRIBER: phone="123", area_code="999";
CREATE_SUBSCRIBER: phone="456", area_code="999";
----

Из примера видно, что каждая строка содержит одно изменяемое значение (`phone`) и одно неизменяемое (`area_code`), которое разумно вынести в параметры для переиспользования шаблона с другими значениями `area_code` в дальнейшем.

Таким образом, соответствующий текст шаблона:

----
CREATE_SUBSCRIBER: phone="%(_csv0)", area_code="%(area_code)"
----

Возвращаясь к примеру, если список для замены имеет вид:

----
123,aaa
456,bbb
789,ccc
----

_..._ а в таблице параметров создан параметр `area_code` с типом `CONSTANT`, которому назначено значение `999`, то будет сгенерирован текстовый файл:

----
CREATE_SUBSCRIBER: phone="123", area_code="999";
CREATE_SUBSCRIBER: phone="456", area_code="999";
CREATE_SUBSCRIBER: phone="789", area_code="999";
----

Параметр `_csv1` был проигнорирован, поскольку соответствующее ему выражение для замены `%(_csv1)` нигде в шаблоне не фигурирует.
