= Telekit - описание

:nofooter:

Системные требования:

* Поддерживаемые ОС: Windows7+ (x86, x64), Linux (x64);

== Настройка приложения

Выполняется через файл `user.options` в корневом каталоге приложения или через переменные окружения (environment variables). Каждая опция записывается с новой строки, дополнительно поддерживаются любые ключи виртуальной машины Java (JVM).

Список доступных опций в формате `system.property` / `ENVIRONMENT_VARIABLE`:

* `telekit.window.size` / `TELEKIT_WINDOW_SIZE` - позволяет указать предпочитаемый размер окна приложения. По умолчанию
приложение выбирает оптимальный размер окна исходя из разрешения экрана, но такой способ, возможно, не подходит для конфигураций с несколькими мониторами и мониторов с низким разрешением;
* `telekit.window.resizable` / `TELEKIT_WINDOW_RESIZABLE` - разблокирует возможность изменения размера окна приложения;
* `telekit.data.dir` / `TELEKIT_DATA_DIR` - директория в которой сохраняются настройки приложения, включая настройки плагинов. По умолчанию: директория `/data` в корневом каталоге приложения;
* `telekit.plugins.dir` / `TELEKIT_PLUGINS_DIR` - директория в которой сохраняются установленные плагины. По умолчанию: директория `/plugins` в корневом каталоге приложения;
* `telekit.proxy.url` / `TELEKIT_PROXY_URL` - URL HTTP(S) прокси (например `http://10.10.10.10:3128`);
* `telekit.proxy.username` / `TELEKIT_PROXY_USERNAME` - имя пользователя HTTP(S) прокси;
* `telekit.proxy.password` / `TELEKIT_PROXY_PASSWORD` - пароль пользователя HTTP(S) прокси;

Опции в формате `system.property` записываются в файле `user.options` как `-Dsystem.property`;

```
-Xmx256M // ограничить использование оперативной памяти 256Mb
-Dtelekit.window.size=800x600
-Dtelekit.window.resizable
-Dtelekit.data.dir=C:/путь/к/любому/каталогу
-Dtelekit.proxy.url=http://10.10.10.10:3128
-Dtelekit.proxy.username=admin
-Dtelekit.proxy.password=123456
```

Переменные окружения настраиваются в зависимости от операционной системы, способом определенным для данной операционной системы.

== Обновление

Для обновления приложения просто скачайте каталог с новой версией и перенесите в него текущие настройки (каталог `data/` и файл `user.options`) и плагины (каталог `plugins/`).

== Меню File

* Plugin Manager - запуск менеджера плагинов;
* Restart - рестарт приложения;
* Quit - выход из приложения.

=== Plugin Manager

В правой части окна отображаются установленные плагины, в левой - детальная информация по выделенному плагину.

===== Опции

* Install / Uninstall - инсталляция / деинсталляция плагина (требуется рестарт приложения);
* Enable / Disable - включение / отключение плагина;
* Show Docs - отображение документации к плагину, при ее наличии.

Для завершения инсталляции или деинсталляции плагина необходимо выполнить рестарт приложения.

== Меню Tools

Здесь собраны стандартные утилиты, которые поставляются вместе с приложением.

=== API Client

include::tools/api_client/index.adoc[]

=== Base64 Encoder

include::tools/base64_encoder/index.adoc[]

=== Import File Builder

include::tools/import_file_builder/index.adoc[]

=== IP Calculator

include::tools/ip_calculator/index.adoc[]

=== Password Generator

include::tools/password_generator/index.adoc[]

=== Sequence Generator

include::tools/sequence_generator/index.adoc[]

=== SS7 Utils

include::tools/ss7/index.adoc[]

=== Transliterator

include::tools/transliterator/index.adoc[]

== Меню Window

===== Опции

* Set always on top - активирует отображение окна приложения поверх всех остальных открытых окон операционной системы.


