package org.telekit.ui.tools.import_file_builder;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.jetbrains.annotations.NotNull;

import java.util.Comparator;
import java.util.Objects;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Param implements Comparable<Param>, Cloneable {

    public static final Comparator<Param> COMPARATOR = Comparator.comparing(Param::getName);

    public static final int MIN_PASSWORD_LENGTH = 8;
    public static final int MAX_PASSWORD_LENGTH = 32;
    public static final int DEFAULT_PASSWORD_LENGTH = 16;

    private String name;
    private Type type = Type.CONSTANT;
    private Integer length;
    private @JsonIgnore String value;

    public Param() {}

    public Param(String name, Type type, Integer length) {
        this.name = name;
        this.type = type;
        this.length = length;
    }

    public Param(Param param) {
        this.name = param.name;
        this.type = param.type;
        this.length = param.length;
        this.value = param.value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Integer getLength() {
        return length;
    }

    public void setLength(Integer length) {
        this.length = length;
    }

    @JsonIgnore
    public boolean isAutoGenerated() {
        return type != Type.CONSTANT;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Param param = (Param) o;
        return name.equals(param.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name);
    }

    @Override
    public String toString() {
        return "Param{" +
                "name='" + name + '\'' +
                ", type='" + type + '\'' +
                ", value='" + value + '\'' +
                ", length=" + length +
                '}';
    }

    @Override
    public int compareTo(@NotNull Param other) {
        return COMPARATOR.compare(this, other);
    }

    public enum Type {
        CONSTANT,
        PASSWORD,
        PASSWORD_BASE64,
        UUID
    }
}