= Telekit - описание

:nofooter:

== Настройка приложения

По умолчанию, все настройки, включая плагины, хранятся в каталоге `data/`, который находится в каталоге установки приложения. Это позволяет перемещать приложение со всеми настройками на внешнем носителе. Доступ к ним осуществляется через меню **Файл > Настройки**.

Вы также можете хранить настройки приложения в домашнем каталоге пользователя или любом другом каталоге по своему усмотрению. Для этого используйте системные свойства (system properties), которые указываются в файле `user.options`, или переменные окружения (environment variables).

Список доступных настроек (в формате `system_property` / `ENVIRONMENT_VARIABLE`):

* `telekit.data.dir` / `TELEKIT_DATA_DIR` - директория, в которой должны храниться настройки приложения. Укажите полный путь к любому каталогу или используйте специальное значение `$HOME`. Последний вариант означает, что приложение будет хранить настройки в домашнем каталоге пользователя. В зависимости от операционной системы: `%LOCALAPPDATA%/Telekit` - для Windows, `~/.config/Telekit` - для Linux. Вы всегда можете найти свои настройки, используя меню **Файл > Конфигурация  > Открыть каталог настроек**;

Опции в формате `system_property` записываются в файле `user.options` как `-Dsystem_property`. Кроме настроек приложения в нем также можно указать любые ключи, которые поддерживаются виртуальной машиной Java (JVM).

----
-Dtelekit.data.dir=$HOME
-Xmx256M // ограничить использование оперативной памяти 256Mb
----

Переменные окружения настраиваются в зависимости от операционной системы, способом определенным для данной операционной системы.

== Обновление

Для обновления приложения распакуйте архив с новой версией и перенесите в него текущие настройки:

- каталог `data/` (если вы не храните данные в домашнем каталоге пользователя);
- файл `user.options` (если вы его изменяли).

При необходимости обновите ярлыки. Старую версию можно удалить.

== Автодополнение и подсказки

Если значение какого-либо параметра всегда ограничено выбором из заранее заданного диапазона значений, то вы можете использовать подсказки (suggestions) для того чтобы не вводить эти значения каждый раз вручную, а выбирать из заранее подготовленного списка.

Предположим, что некоторый шаблон содержит параметр `country_code`, в котором необходимо каждый раз указывать телефонный код страны. Вы можете упростить задачу сразу создав готовый справочник из наиболее часто используемых значений.

* Выберите **Файл > Конфигурация  > Открыть каталог настроек** и перейдите в каталог *autocomplete*;
* Создайте файл с расширением https://ru.wikipedia.org/wiki/.properties[`.properties`], имя которого совпадает со именем параметра в шаблоне.
+
Обратите внимание, что если в файле используются символы не латинского алфавита, то кодировка должна быть UTF-8.
+
* В файле укажите возможные значения параметра - каждое с новой строки:
+
.country_code.properties
[source,properties]
----
Russia=7
Germany=49
China=86
----
+

Если теперь в соответствующем шаблоне вы видите значок *&#128161;* рядом с именем параметра, то сделанные изменения подхватились автоматически. Используйте контекстное меню (опция *Выбрать значение*), чтобы указать значение параметра.

== Инструменты

В этом меню собраны утилиты, которые поставляются вместе с приложением.

[NOTE]
====
Некоторые утилиты используют специальный синтаксис для подстановки указанных пользователем значений в определенное место строки или документа.

*Placeholder* - это выражение вида `%(parameter_name)`, которое будет заменено в процессе работы утилиты. Значение, которое может принимать _placeholder_ либо явно задается пользователем, либо генерируется автоматически.

Если вы знакомы с шаблонизаторами (например, https://mustache.github.io[Mustache]), то это самый элементарный пример одного из них.
====


=== API клиент

include::tools/api_client/index.adoc[]


=== Base64 декодер

include::tools/base64_encoder/index.adoc[]


=== Генератор файлов импорта

include::tools/import_file_builder/index.adoc[]


=== IP калькулятор

include::tools/ip_calculator/index.adoc[]


=== Генератор паролей

include::tools/password_generator/index.adoc[]


=== Генератор последовательностей

include::tools/sequence_generator/index.adoc[]


=== ОКС-7

include::tools/ss7/index.adoc[]


=== Транслитерация

include::tools/transliterator/index.adoc[]
