package org.telekit.desktop.tools.common;

import javafx.scene.control.TableRow;
import javafx.scene.control.cell.TextFieldTableCell;
import javafx.util.StringConverter;

public class ParamValueTableCell extends TextFieldTableCell<Param, String> {

    public ParamValueTableCell(StringConverter<String> converter) {
        super(converter);
    }

    @Override
    public void updateItem(String value, boolean empty) {
        super.updateItem(value, empty);

        TableRow<Param> row = getTableRow();
        if (row == null) return;

        Param param = row.getItem();
        String text;
        if (param != null) {
            setEditable(!param.isAutoGenerated());
            if (param.isAutoGenerated()) {
                text = param.getType().name() + (param.getLength() > 0 ? ": " + param.getLength() : "");
                setText(text);
            }
        }
    }
}